name: make and commit file

on:
  schedule:
    - cron: '*/5 * * * *' # At 00:00 on Monday

jobs:
  My_tests:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ½ï¸ Checkout the repo
        uses: actions/checkout@v2 # checkout the repository content to github runner

      # - name: ðŸ Set up Python 3.8
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'

      # - name: ðŸ’¿ Install python-telegram-bot Python package
      #   run: pip install python-telegram-bot

      # - name: ðŸ“¥ Download the Python script needed for automation
      #   run:  curl https://raw.githubusercontent.com/u2u4u/streamlitproj/main/app.py -o run.py

      # - name: execute py script # run main.py
      #   env:
      #     SOME_SECRET: ${{ secrets.SENDMESS_TOKEM }}
      #   run: python sendmessage.py

      # - name: ðŸš€ Run Automation
      #   run: python sendmessage.py ${{ secrets.SENDMESS_TOKEM }}
      - name: makenewfile
        run: |
          file_name=test_files.txt
          current_time=$(date "+%Y.%m.%d-%H.%M.%S")
          echo "print('$current_time')" > printest.py

      - name: commit files
        run: |
          git config --local user.email "soheilipour@gmail.com"
          git config --local user.name "u2u4u"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 